### ISSUE TITLE
npm module name is already in use

### ISSUE THREAD

**Issue by meyer** [oysterbooks/oy#6]
I just wasted an impressive amount of time trying to figure out why `oy` didn’t have a `renderTemplate` method. Turns out I had installed [the wrong `oy`](https://github.com/cistov/oy). Looks like @cistov beat you all to that URL by a few years.

me right now:
![the-avengers-angry-hulk-smash-loki](https://cloud.githubusercontent.com/assets/13781/8920844/5e3aadb6-3483-11e5-8437-2d8880b10b42.gif)

`oyvey` and `oy-vey` are available. Installing from Github works pretty well, too.

Aaaaaaaaaanyways. if you need me, I’ll be over here, yelling into a pillow until my yeller can’t yell no more.

**Comment by revivek** [comment]
Augh! What a detail to overlook. I think `oyvey` or `oy-vey` works for now and will publish tomorrow. In the meantime, the PR works—accepting. Thanks @meyer! Excited to get this off the ground.

**Comment by revivek** [comment]
Updated. Published under `oy-vey`.
